apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobia-polyglot
spec:
  selector:
    matchLabels:
      app: cobia-polyglot
  replicas: 1
  template:
    metadata:
      labels:
        app: cobia-polyglot
    spec:
     containers:
     - name: container-polygot
       image: gcr.io/k8s-cobia/polyglot-1.0
       resources:
         limits:
           memory: "64Mi"
           cpu: "110m"
         requests:
           memory: "64Mi"
           cpu: "100m"
       ports:
       - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: cobia-polyglot-service
  labels:
    app: cobia-polyglot
spec:
  type: ClusterIP
  selector:
    app: cobia-polyglot
  ports:
    - port: 8084
      targetPort: 8084

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cobia-polyglot-hpa-mem
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cobia-polyglot
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cobia-polyglot-hpa-cpu
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cobia-polyglot
  targetCPUUtilizationPercentage: 50
